apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesJson6902:
  - path: patch-channel.yaml
    target:
      group: operators.coreos.com
      kind: Subscription
      name: nfd 
      version: v1alpha1
      namespace: openshift-operators