apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  namespace: openshift-operators-redhat
  name: openshift-operators-redhat
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  namespace: openshift-logging
  name: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  targetNamespaces:
    - openshift-logging