apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali 
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: platform-apps
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: platform-apps
  source:
    path: manifests/kiali/overlays/stable
    repoURL: https://github.com/pumphouse-p/shiftops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true