apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: file-integrity-app
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "11"
  labels:
    gitops.ownedBy: platform-apps
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: platform-apps
  source:
    path: manifests/file-integrity/base
    repoURL: https://github.com/pumphouse-p/shiftops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true