apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

bases:
  - ../../../argocd/apps/oauth/base
  - ../../../argocd/apps/resource-locker/base
  - ../../../argocd/apps/roles-and-bindings/base
  - ../../../argocd/apps/prometheus-user-monitoring/base
  - ../../../argocd/apps/openshift-logging/base
  - ../../../argocd/apps/node-feature-discovery/overlays/4.7