apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/cnv-app.yaml

patchesJson6902:
  - target:
      group: argoproj.io
      kind: Application
      version: v1alpha1
      name: cnv
    path: emulation-patch.yaml