apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnv-node-label-clusterrole
  namespace: openshift-cnv
  annotations:
    argocd.argoproj.io/hook: PreSync
rules:
  - apiGroups:
    - ""
    resources:
      - nodes
      - node
    verbs:
      - list
      - get
      - watch
      - create
      - update
      - patch