apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "11"
  labels:
    gitops.ownedBy: demo-apps
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: demo-apps
  source:
    path: manifests/demos/bookinfo/base
    repoURL: https://github.com/pumphouse-p/shiftops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
