apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: odf-node-label-rolebinding
  annotations:
    argocd.argoproj.io/hook: PreSync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cnv-node-label-clusterrole
subjects:
  - kind: ServiceAccount
    name: odf-node-label-sa
    namespace: openshift-storage