apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kuard-sm
  labels:
    release: user-workload-monitoring
    app: kuard
spec:
  namespaceSelector:
    matchNames:
    - kuard
  selector:
    matchLabels:
      app: kuard
  endpoints:
  - port: http
    interval: 15s
    path: /metrics