apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resource-locker
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/resource-locker/base
    repoURL: https://github.com/pumphouse-p/shiftops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true