apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - https://github.com/redhat-cop/gitops-catalog/catalog/sealed-secrets-operator/overlays/default

resources:
  - namespace.yaml