apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
  - target:
      kind: Application
      name: advanced-cluster-management
    patch: |
      - op: replace
        path: /spec/source/path
        value: manifests/acm/overlays/2.3